// 2D geometry for SVG and the DOM: points, rectangles, view boxes and affine transform matrices.

export type { Point } from './point';
export type { Rect } from './rect';
export type { Size } from './size';
export { getDistance } from './get-distance';
export { lerpPoint } from './lerp-point';
export { polarToCartesian } from './polar-to-cartesian';
export { getHeadingBetween } from './get-heading-between';
export { rotatePoint } from './rotate-point';
export { getBoundingRect } from './get-bounding-rect';
export { getRectCenter } from './get-rect-center';
export { isPointInRect } from './is-point-in-rect';
export { getRectIntersection } from './get-rect-intersection';
export { getRectUnion } from './get-rect-union';
export { insetRect } from './inset-rect';
export type { Insets } from './inset-rect';
export { fitRect } from './fit-rect';
export type { FittedRect } from './fitted-rect';
export { formatViewBox } from './format-view-box';
export { parseViewBox } from './parse-view-box';
export { createIdentityMatrix } from './create-identity-matrix';
export type { Matrix2D } from './matrix-2d';
export { multiplyMatrices } from './multiply-matrices';
export { createTranslationMatrix } from './create-translation-matrix';
export { createRotationMatrix } from './create-rotation-matrix';
export { createScaleMatrix } from './create-scale-matrix';
export { transformDelta } from './transform-delta';
export { transformPoint } from './transform-point';
export { invertMatrix } from './invert-matrix';
export { composeMatrix } from './compose-matrix';
export type { DecomposedTransform } from './decomposed-transform';
export { decomposeMatrix } from './decompose-matrix';
export { resetMatrixRotationAndFlip } from './reset-matrix-rotation-and-flip';
export { screenDeltaToLocal } from './screen-delta-to-local';
export { parseTransform } from './parse-transform';
export { formatMatrix } from './format-matrix';
export { transformRect } from './transform-rect';
export type { Anchor } from './anchor';
export { getAnchorPoint } from './get-anchor-point';
export { placeRect } from './place-rect';
export type { PlaceRectOptions } from './place-rect';
export { resizeRect } from './resize-rect';
export { scaleRect } from './scale-rect';
export { clipSegment } from './clip-segment';
export { clipPolyline } from './clip-polyline';
export { snapToGrid } from './snap-to-grid';
export { getDistanceToSegment } from './get-distance-to-segment';
export { isPointInPolygon } from './is-point-in-polygon';
export { isPointInTransformedRect } from './is-point-in-transformed-rect';
export { getPolygonArea } from './get-polygon-area';
export { getPolygonCentroid } from './get-polygon-centroid';
export { centerMatrixOn } from './center-matrix-on';
export { getMatrixRotation } from './get-matrix-rotation';
export { isMatrixFlipped } from './is-matrix-flipped';
export { moveMatrix } from './move-matrix';
export { resetMatrixFlip } from './reset-matrix-flip';
export { resetMatrixRotation } from './reset-matrix-rotation';
export { getArcLength } from './get-arc-length';
export { formatMatrixSimple } from './format-matrix-simple';
export { fitRectSimple } from './fit-rect-simple';
export { scaleRectSimple } from './scale-rect-simple';
export { placeRectSimple } from './place-rect-simple';
