// 2D geometry for SVG and the DOM: points, rectangles, view boxes and affine transform matrices.

export type { Point } from './point.ts';
export type { Rect } from './rect.ts';
export type { Size } from './size.ts';
export { distance } from './distance.ts';
export { lerpPoint } from './lerp-point.ts';
export { polarToCartesian } from './polar-to-cartesian.ts';
export { headingBetween } from './heading-between.ts';
export { rotatePoint } from './rotate-point.ts';
export { boundingRect } from './bounding-rect.ts';
export { rectCenter } from './rect-center.ts';
export { rectContainsPoint } from './rect-contains-point.ts';
export { rectIntersection } from './rect-intersection.ts';
export { rectUnion } from './rect-union.ts';
export { insetRect } from './inset-rect.ts';
export type { Insets } from './insets.ts';
export { fitRect } from './fit-rect.ts';
export type { FittedRect } from './fitted-rect.ts';
export { formatViewBox } from './format-view-box.ts';
export { parseViewBox } from './parse-view-box.ts';
export { identityMatrix } from './identity-matrix.ts';
export type { Matrix2D } from './matrix-2d.ts';
export { multiplyMatrices } from './multiply-matrices.ts';
export { translationMatrix } from './translation-matrix.ts';
export { rotationMatrix } from './rotation-matrix.ts';
export { scaleMatrix } from './scale-matrix.ts';
export { transformDelta } from './transform-delta.ts';
export { transformPoint } from './transform-point.ts';
export { invertMatrix } from './invert-matrix.ts';
export { composeMatrix } from './compose-matrix.ts';
export type { DecomposedTransform } from './decomposed-transform.ts';
export { decomposeMatrix } from './decompose-matrix.ts';
export { removeRotationAndFlip } from './remove-rotation-and-flip.ts';
export { screenDeltaToLocal } from './screen-delta-to-local.ts';
export { parseTransform } from './parse-transform.ts';
export { formatMatrix } from './format-matrix.ts';
export { transformRect } from './transform-rect.ts';
export type { Anchor } from './anchor.ts';
export { getAnchorPoint } from './get-anchor-point.ts';
export { placeRect } from './place-rect.ts';
export type { PlaceRectOptions } from './place-rect-options.ts';
export { resizeRect } from './resize-rect.ts';
export { scaleRect } from './scale-rect.ts';
export { clipSegment } from './clip-segment.ts';
export { clipPolyline } from './clip-polyline.ts';
export { snapToGrid } from './snap-to-grid.ts';
export { distanceToSegment } from './distance-to-segment.ts';
export { isPointInPolygon } from './is-point-in-polygon.ts';
export { isPointInTransformedRect } from './is-point-in-transformed-rect.ts';
export { getPolygonArea } from './get-polygon-area.ts';
export { getPolygonCentroid } from './get-polygon-centroid.ts';
export { centerMatrixOn } from './center-matrix-on.ts';
export { getMatrixRotation } from './get-matrix-rotation.ts';
export { isMatrixFlipped } from './is-matrix-flipped.ts';
export { moveMatrix } from './move-matrix.ts';
export { removeFlip } from './remove-flip.ts';
export { removeRotation } from './remove-rotation.ts';
export { getArcLength } from './get-arc-length.ts';
