// Comment prefixes: `Custom` = project choice (non-standard), `Off` = disabled on purpose, `Deprecated` = replaced.
// eslint-plugin-unicorn: every rule is listed. Preset rules are errors (warnings count as errors anyway); the others are commented.
// Rules about CSS, the DOM or Node APIs the library does not use stay listed: they cost nothing.

import unicorn from 'eslint-plugin-unicorn';
import { CODE_FILES } from './files.mjs';

/**
 * Unicorn rules (modern, consistent JavaScript), for any project.
 *
 * @returns {import('eslint').Linter.Config[]} The configs of the block, to spread in `defineConfig([…])`.
 */
export default function unicornBlock() {
  return [
    {
      name: 'unicorn',
      files: CODE_FILES,
      plugins: {
        unicorn,
      },
      rules: {
        'unicorn/better-dom-traversing': ['error'],
        // Deprecated: replaced by eslint-plugin-regexp.
        'unicorn/better-regex': ['off'],
        'unicorn/catch-error-name': ['error'],
        'unicorn/class-reference-in-static-methods': ['error'],
        'unicorn/comment-content': ['off'],
        'unicorn/consistent-arrow-return-style': ['off'],
        'unicorn/consistent-assert': ['error'],
        // Custom: API function names come from the specification (`shallowEqual`, `meetsContrastLevel`);
        // predicate callbacks are named after their role.
        'unicorn/consistent-boolean-name': ['error', { checkFunctions: 'never', ignore: ['^predicate$', '^guard$'] }],
        // Off: duplicate of @typescript-eslint/member-ordering.
        'unicorn/consistent-class-member-order': ['off'],
        'unicorn/consistent-compound-words': ['error'],
        'unicorn/consistent-conditional-object-spread': ['error'],
        'unicorn/consistent-date-clone': ['error'],
        // Custom.
        'unicorn/consistent-destructuring': ['error'],
        'unicorn/consistent-empty-array-spread': ['error'],
        'unicorn/consistent-existence-index-check': ['error'],
        'unicorn/consistent-export-decorator-position': ['error'],
        'unicorn/consistent-function-scoping': ['error'],
        'unicorn/consistent-function-style': ['off'],
        'unicorn/consistent-json-file-read': ['error'],
        'unicorn/consistent-optional-chaining': ['error'],
        'unicorn/consistent-template-literal-escape': ['error'],
        'unicorn/consistent-tuple-labels': ['error'],
        // Custom: error subclasses set their name and message.
        'unicorn/custom-error-definition': ['error'],
        'unicorn/default-export-style': ['error'],
        'unicorn/dom-node-dataset': ['error'],
        // Off: formatting is Prettier's job.
        'unicorn/empty-brace-spaces': ['off'],
        'unicorn/error-message': ['error'],
        'unicorn/escape-case': ['error'],
        'unicorn/expiring-todo-comments': ['error'],
        'unicorn/explicit-length-check': ['error'],
        'unicorn/explicit-timer-delay': ['error'],
        // Off: duplicate of check-file/filename-naming-convention.
        'unicorn/filename-case': ['off'],
        'unicorn/id-match': ['off'],
        'unicorn/import-style': ['error'],
        'unicorn/isolated-functions': ['error'],
        // Custom.
        'unicorn/iteration-fallback-style': ['error'],
        // Off: duplicate of the core logical-assignment-operators.
        'unicorn/logical-assignment-operators': ['off'],
        'unicorn/max-nested-calls': ['error'],
        'unicorn/name-replacements': ['error'],
        'unicorn/new-for-builtins': ['error'],
        // Off: duplicate of @eslint-community/eslint-comments/no-unlimited-disable.
        'unicorn/no-abusive-eslint-disable': ['off'],
        'unicorn/no-accessor-recursion': ['error'],
        'unicorn/no-accidental-bitwise-operator': ['error'],
        // Off: duplicate of import-x/no-anonymous-default-export.
        'unicorn/no-anonymous-default-export': ['off'],
        'unicorn/no-array-callback-reference': ['error'],
        'unicorn/no-array-concat-in-loop': ['error'],
        'unicorn/no-array-fill-with-reference-type': ['error'],
        'unicorn/no-array-from-fill': ['error'],
        // Custom: `unshift` / `shift` are O(n).
        'unicorn/no-array-front-mutation': ['error'],
        'unicorn/no-array-method-this-argument': ['error'],
        // Deprecated: replaced by unicorn/prefer-single-call.
        'unicorn/no-array-push-push': ['off'],
        'unicorn/no-array-reduce': ['error'],
        'unicorn/no-array-reverse': ['error'],
        'unicorn/no-array-sort': ['error'],
        'unicorn/no-array-sort-for-min-max': ['error'],
        'unicorn/no-array-splice': ['error'],
        'unicorn/no-asterisk-prefix-in-documentation-comments': ['off'],
        'unicorn/no-async-iterator-callback': ['error'],
        'unicorn/no-async-promise-finally': ['error'],
        'unicorn/no-await-expression-member': ['error'],
        'unicorn/no-await-in-promise-methods': ['error'],
        'unicorn/no-barrel-files': ['off'],
        'unicorn/no-blob-to-file': ['error'],
        'unicorn/no-boolean-sort-comparator': ['error'],
        'unicorn/no-break-in-nested-loop': ['error'],
        'unicorn/no-canvas-to-image': ['error'],
        'unicorn/no-chained-comparison': ['error'],
        'unicorn/no-collection-bracket-access': ['error'],
        'unicorn/no-computed-property-existence-check': ['error'],
        'unicorn/no-confusing-array-splice': ['error'],
        'unicorn/no-confusing-array-with': ['error'],
        'unicorn/no-console-spaces': ['error'],
        'unicorn/no-constant-zero-expression': ['error'],
        'unicorn/no-declarations-before-early-exit': ['error'],
        'unicorn/no-deprecated-css-features': ['off'],
        'unicorn/no-document-cookie': ['error'],
        'unicorn/no-double-comparison': ['error'],
        'unicorn/no-duplicate-css-selectors': ['off'],
        'unicorn/no-duplicate-font-family-names': ['off'],
        // Off: duplicate of sonarjs/no-duplicated-branches.
        'unicorn/no-duplicate-if-branches': ['off'],
        'unicorn/no-duplicate-logical-operands': ['error'],
        'unicorn/no-duplicate-loops': ['error'],
        'unicorn/no-duplicate-set-values': ['error'],
        'unicorn/no-empty-file': ['error'],
        'unicorn/no-error-property-assignment': ['error'],
        'unicorn/no-exports-in-scripts': ['error'],
        'unicorn/no-for-each': ['error'],
        'unicorn/no-for-loop': ['error'],
        'unicorn/no-global-object-property-assignment': ['error'],
        // Deprecated: replaced by unicorn/prefer-unicode-code-point-escapes.
        'unicorn/no-hex-escape': ['off'],
        'unicorn/no-immediate-mutation': ['error'],
        'unicorn/no-impossible-length-comparison': ['error'],
        'unicorn/no-incorrect-query-selector': ['error'],
        'unicorn/no-incorrect-template-string-interpolation': ['error'],
        // Deprecated: replaced by unicorn/no-instanceof-builtins.
        'unicorn/no-instanceof-array': ['off'],
        'unicorn/no-instanceof-builtins': ['error'],
        // Off: already a TypeScript compiler error.
        'unicorn/no-invalid-argument-count': ['off'],
        'unicorn/no-invalid-character-comparison': ['error'],
        'unicorn/no-invalid-fetch-options': ['error'],
        'unicorn/no-invalid-file-input-accept': ['off'],
        'unicorn/no-invalid-media-features': ['off'],
        'unicorn/no-invalid-remove-event-listener': ['error'],
        'unicorn/no-invalid-well-known-symbol-methods': ['error'],
        'unicorn/no-keyword-prefix': ['off'],
        'unicorn/no-late-current-target-access': ['error'],
        'unicorn/no-late-event-control': ['error'],
        // Deprecated: replaced by unicorn/no-unnecessary-slice-end.
        'unicorn/no-length-as-slice-end': ['off'],
        'unicorn/no-lonely-if': ['error'],
        'unicorn/no-loop-iterable-mutation': ['error'],
        'unicorn/no-magic-array-flat-depth': ['error'],
        'unicorn/no-manually-wrapped-comments': ['off'],
        'unicorn/no-mismatched-map-key': ['error'],
        'unicorn/no-misrefactored-assignment': ['error'],
        'unicorn/no-missing-local-resource': ['off'],
        'unicorn/no-multiple-promise-resolver-calls': ['error'],
        // Off: duplicate of import-x/no-named-default.
        'unicorn/no-named-default': ['off'],
        'unicorn/no-negated-array-predicate': ['error'],
        'unicorn/no-negated-comparison': ['error'],
        'unicorn/no-negated-condition': ['error'],
        'unicorn/no-negation-in-equality-check': ['error'],
        // Off: duplicate of the core no-nested-ternary; its parentheses fight Prettier.
        'unicorn/no-nested-ternary': ['off'],
        'unicorn/no-nesting-with-mixed-specificity': ['off'],
        'unicorn/no-new-array': ['error'],
        'unicorn/no-new-buffer': ['error'],
        'unicorn/no-non-function-verb-prefix': ['error'],
        'unicorn/no-nonstandard-builtin-properties': ['error'],
        // Custom: `null` only where an API requires it (prototypes, JSON); specs and configs are exempt below.
        'unicorn/no-null': ['error'],
        'unicorn/no-object-as-default-parameter': ['error'],
        'unicorn/no-object-methods-with-collections': ['error'],
        'unicorn/no-optional-chaining-on-undeclared-variable': ['error'],
        'unicorn/no-process-exit': ['error'],
        'unicorn/no-redundant-comparison': ['error'],
        'unicorn/no-redundant-nested-style-rules': ['off'],
        'unicorn/no-return-array-push': ['error'],
        'unicorn/no-selector-as-dom-name': ['error'],
        'unicorn/no-shorthand-property-overrides': ['error'],
        'unicorn/no-single-promise-in-promise-methods': ['error'],
        // Off: duplicate of @typescript-eslint/no-extraneous-class.
        'unicorn/no-static-only-class': ['off'],
        'unicorn/no-subtraction-comparison': ['error'],
        'unicorn/no-thenable': ['error'],
        // Off: duplicate of @typescript-eslint/no-this-alias.
        'unicorn/no-this-assignment': ['off'],
        'unicorn/no-this-outside-of-class': ['error'],
        'unicorn/no-top-level-assignment-in-function': ['error'],
        'unicorn/no-top-level-side-effects': ['error'],
        'unicorn/no-transition-all': ['error'],
        'unicorn/no-typeof-undefined': ['error'],
        'unicorn/no-uncalled-method': ['error'],
        'unicorn/no-undeclared-class-members': ['error'],
        'unicorn/no-unknown-css-annotations': ['off'],
        'unicorn/no-unknown-pseudo-selectors': ['off'],
        'unicorn/no-unnecessary-array-flat-depth': ['error'],
        'unicorn/no-unnecessary-array-flat-map': ['error'],
        'unicorn/no-unnecessary-array-splice-count': ['error'],
        // Off: duplicate of @typescript-eslint/await-thenable.
        'unicorn/no-unnecessary-await': ['off'],
        'unicorn/no-unnecessary-boolean-comparison': ['error'],
        'unicorn/no-unnecessary-fetch-options': ['error'],
        'unicorn/no-unnecessary-global-this': ['error'],
        'unicorn/no-unnecessary-nested-ternary': ['error'],
        'unicorn/no-unnecessary-polyfills': ['error'],
        'unicorn/no-unnecessary-slice-end': ['error'],
        'unicorn/no-unnecessary-splice': ['error'],
        'unicorn/no-unnecessary-string-trim': ['error'],
        'unicorn/no-unreadable-array-destructuring': ['error'],
        'unicorn/no-unreadable-for-of-expression': ['error'],
        'unicorn/no-unreadable-iife': ['error'],
        // Custom.
        'unicorn/no-unreadable-new-expression': ['error'],
        'unicorn/no-unreadable-object-destructuring': ['error'],
        'unicorn/no-unsafe-buffer-conversion': ['error'],
        // Custom.
        'unicorn/no-unsafe-dom-html': ['error'],
        'unicorn/no-unsafe-promise-all-settled-values': ['error'],
        'unicorn/no-unsafe-property-key': ['error'],
        'unicorn/no-unsafe-sqlite-interpolation': ['error'],
        'unicorn/no-unsafe-string-replacement': ['error'],
        'unicorn/no-unscoped-css-nesting-selector': ['off'],
        // Deprecated: replaced by unicorn/no-unused-builtin-method-return.
        'unicorn/no-unused-array-method-return': ['off'],
        // Off: duplicate of sonarjs/no-ignored-return.
        'unicorn/no-unused-builtin-method-return': ['off'],
        'unicorn/no-unused-iterator-helper': ['error'],
        // Custom.
        'unicorn/no-unused-properties': ['error'],
        'unicorn/no-useless-boolean-cast': ['error'],
        'unicorn/no-useless-coercion': ['error'],
        'unicorn/no-useless-collection-argument': ['error'],
        'unicorn/no-useless-compound-assignment': ['error'],
        // Off: duplicate of the core no-useless-concat.
        'unicorn/no-useless-concat': ['off'],
        'unicorn/no-useless-continue': ['error'],
        'unicorn/no-useless-delete-check': ['error'],
        // Off: duplicate of the core no-else-return.
        'unicorn/no-useless-else': ['off'],
        'unicorn/no-useless-error-capture-stack-trace': ['error'],
        'unicorn/no-useless-fallback-in-spread': ['error'],
        'unicorn/no-useless-iterator-to-array': ['error'],
        'unicorn/no-useless-length-check': ['error'],
        'unicorn/no-useless-logical-operand': ['error'],
        'unicorn/no-useless-override': ['error'],
        'unicorn/no-useless-promise-resolve-reject': ['error'],
        'unicorn/no-useless-re-export': ['error'],
        'unicorn/no-useless-recursion': ['error'],
        'unicorn/no-useless-set-construction': ['error'],
        'unicorn/no-useless-spread': ['error'],
        'unicorn/no-useless-switch-case': ['error'],
        'unicorn/no-useless-template-literals': ['error'],
        'unicorn/no-useless-undefined': ['error'],
        'unicorn/no-using-resource-escape': ['error'],
        'unicorn/no-xor-as-exponentiation': ['error'],
        'unicorn/no-zero-fractions': ['error'],
        // Off: formatting is Prettier's job.
        'unicorn/number-literal-case': ['off'],
        'unicorn/numeric-separators-style': ['error'],
        // Off: duplicate of the core operator-assignment.
        'unicorn/operator-assignment': ['off'],
        'unicorn/prefer-abort-signal-any': ['error'],
        'unicorn/prefer-abort-signal-timeout': ['error'],
        'unicorn/prefer-add-event-listener': ['error'],
        'unicorn/prefer-add-event-listener-options': ['error'],
        'unicorn/prefer-aggregate-error': ['error'],
        'unicorn/prefer-array-find': ['error'],
        'unicorn/prefer-array-flat': ['error'],
        'unicorn/prefer-array-flat-map': ['error'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-array-from-async': ['off'],
        'unicorn/prefer-array-from-map': ['error'],
        'unicorn/prefer-array-from-range': ['error'],
        'unicorn/prefer-array-index-of': ['error'],
        'unicorn/prefer-array-iterable-methods': ['error'],
        'unicorn/prefer-array-last-methods': ['error'],
        'unicorn/prefer-array-slice': ['error'],
        'unicorn/prefer-array-some': ['error'],
        'unicorn/prefer-at': ['error'],
        'unicorn/prefer-await': ['error'],
        'unicorn/prefer-bigint-literals': ['error'],
        'unicorn/prefer-blob-reading-methods': ['error'],
        'unicorn/prefer-block-statement-over-iife': ['error'],
        'unicorn/prefer-boolean-return': ['error'],
        'unicorn/prefer-class-fields': ['error'],
        'unicorn/prefer-classlist-toggle': ['error'],
        'unicorn/prefer-code-point': ['error'],
        'unicorn/prefer-combined-guards': ['error'],
        // Off: conflicts with the core no-continue (early `continue` is forbidden).
        'unicorn/prefer-continue': ['off'],
        'unicorn/prefer-date-now': ['error'],
        'unicorn/prefer-default-parameters': ['error'],
        'unicorn/prefer-direct-iteration': ['error'],
        'unicorn/prefer-dispose': ['off'],
        'unicorn/prefer-dom-node-append': ['error'],
        // Deprecated: replaced by unicorn/dom-node-dataset.
        'unicorn/prefer-dom-node-dataset': ['off'],
        'unicorn/prefer-dom-node-html-methods': ['error'],
        'unicorn/prefer-dom-node-remove': ['error'],
        'unicorn/prefer-dom-node-replace-children': ['error'],
        'unicorn/prefer-dom-node-text-content': ['error'],
        'unicorn/prefer-early-return': ['error'],
        'unicorn/prefer-else-if': ['error'],
        'unicorn/prefer-error-is-error': ['off'],
        'unicorn/prefer-event-target': ['error'],
        'unicorn/prefer-explicit-viewport-units': ['off'],
        'unicorn/prefer-export-from': ['error'],
        'unicorn/prefer-flat-math-min-max': ['error'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-get-or-insert-computed': ['off'],
        'unicorn/prefer-global-number-constants': ['error'],
        'unicorn/prefer-global-this': ['error'],
        'unicorn/prefer-group-by': ['error'],
        'unicorn/prefer-has-check': ['error'],
        'unicorn/prefer-hoisting-branch-code': ['error'],
        'unicorn/prefer-https': ['error'],
        'unicorn/prefer-identifier-import-export-specifiers': ['error'],
        'unicorn/prefer-import-meta-properties': ['off'],
        // Off: duplicate of @typescript-eslint/prefer-includes (type-aware).
        'unicorn/prefer-includes': ['off'],
        'unicorn/prefer-includes-over-repeated-comparisons': ['error'],
        'unicorn/prefer-iterable-in-constructor': ['error'],
        'unicorn/prefer-iterator-concat': ['off'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-iterator-helpers': ['off'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-iterator-to-array': ['off'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-iterator-to-array-at-end': ['off'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-iterator-zip': ['off'],
        'unicorn/prefer-json-import': ['off'],
        // Deprecated: replaced by unicorn/consistent-json-file-read.
        'unicorn/prefer-json-parse-buffer': ['off'],
        'unicorn/prefer-keyboard-event-key': ['error'],
        'unicorn/prefer-location-assign': ['error'],
        'unicorn/prefer-logical-operator-over-ternary': ['error'],
        'unicorn/prefer-map-from-entries': ['error'],
        'unicorn/prefer-math-abs': ['error'],
        'unicorn/prefer-math-constants': ['error'],
        'unicorn/prefer-math-min-max': ['error'],
        'unicorn/prefer-math-trunc': ['error'],
        'unicorn/prefer-media-feature-range-syntax': ['off'],
        'unicorn/prefer-minimal-ternary': ['error'],
        'unicorn/prefer-modern-dom-apis': ['error'],
        'unicorn/prefer-modern-math-apis': ['error'],
        'unicorn/prefer-module': ['error'],
        'unicorn/prefer-native-coercion-functions': ['error'],
        'unicorn/prefer-negative-index': ['error'],
        'unicorn/prefer-node-protocol': ['error'],
        'unicorn/prefer-number-coercion': ['error'],
        'unicorn/prefer-number-is-safe-integer': ['error'],
        'unicorn/prefer-number-properties': ['error'],
        'unicorn/prefer-object-define-properties': ['error'],
        'unicorn/prefer-object-destructuring-defaults': ['error'],
        'unicorn/prefer-object-from-entries': ['error'],
        'unicorn/prefer-object-iterable-methods': ['error'],
        'unicorn/prefer-observer-apis': ['error'],
        'unicorn/prefer-optional-catch-binding': ['error'],
        'unicorn/prefer-path2d': ['error'],
        'unicorn/prefer-private-class-fields': ['error'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-promise-try': ['off'],
        'unicorn/prefer-promise-with-resolvers': ['error'],
        'unicorn/prefer-prototype-methods': ['error'],
        'unicorn/prefer-query-selector': ['error'],
        'unicorn/prefer-queue-microtask': ['error'],
        'unicorn/prefer-reflect-apply': ['error'],
        'unicorn/prefer-regexp-escape': ['off'],
        // Off: duplicate of regexp/prefer-regexp-test.
        'unicorn/prefer-regexp-test': ['off'],
        'unicorn/prefer-response-static-json': ['error'],
        'unicorn/prefer-scoped-selector': ['error'],
        'unicorn/prefer-set-has': ['error'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-set-methods': ['off'],
        'unicorn/prefer-set-size': ['error'],
        'unicorn/prefer-short-arrow-method': ['off'],
        'unicorn/prefer-simple-condition-first': ['error'],
        'unicorn/prefer-simple-sort-comparator': ['error'],
        'unicorn/prefer-simplified-conditions': ['error'],
        'unicorn/prefer-single-array-predicate': ['error'],
        'unicorn/prefer-single-call': ['error'],
        'unicorn/prefer-single-object-destructuring': ['error'],
        'unicorn/prefer-single-replace': ['error'],
        'unicorn/prefer-smaller-scope': ['error'],
        'unicorn/prefer-split-limit': ['error'],
        'unicorn/prefer-spread': ['error'],
        'unicorn/prefer-string-match-all': ['error'],
        'unicorn/prefer-string-pad-start-end': ['error'],
        'unicorn/prefer-string-raw': ['error'],
        'unicorn/prefer-string-repeat': ['error'],
        'unicorn/prefer-string-replace-all': ['error'],
        'unicorn/prefer-string-slice': ['error'],
        // Off: duplicate of @typescript-eslint/prefer-string-starts-ends-with (type-aware).
        'unicorn/prefer-string-starts-ends-with': ['off'],
        'unicorn/prefer-string-trim-start-end': ['error'],
        'unicorn/prefer-structured-clone': ['error'],
        'unicorn/prefer-switch': ['error'],
        'unicorn/prefer-temporal': ['off'],
        // Off: ES2025+ API, the library targets ES2024.
        'unicorn/prefer-temporal-conversion': ['off'],
        'unicorn/prefer-ternary': ['error'],
        'unicorn/prefer-then-catch': ['error'],
        'unicorn/prefer-toggle-attribute': ['error'],
        'unicorn/prefer-top-level-await': ['error'],
        'unicorn/prefer-type-error': ['error'],
        'unicorn/prefer-type-literal-last': ['error'],
        'unicorn/prefer-uint8array-base64': ['off'],
        'unicorn/prefer-uint8array-hex': ['off'],
        'unicorn/prefer-unary-minus': ['error'],
        'unicorn/prefer-unicode-code-point-escapes': ['error'],
        'unicorn/prefer-url-can-parse': ['error'],
        'unicorn/prefer-url-href': ['error'],
        'unicorn/prefer-url-search-parameters': ['error'],
        'unicorn/prefer-while-loop-condition': ['error'],
        // Deprecated: replaced by unicorn/name-replacements.
        'unicorn/prevent-abbreviations': ['off'],
        'unicorn/relative-url-style': ['error'],
        'unicorn/require-array-join-separator': ['error'],
        // Off: duplicate of @typescript-eslint/require-array-sort-compare (type-aware).
        'unicorn/require-array-sort-compare': ['off'],
        'unicorn/require-css-escape': ['error'],
        'unicorn/require-frontmatter-fields': ['off'],
        'unicorn/require-module-attributes': ['error'],
        'unicorn/require-module-specifiers': ['error'],
        'unicorn/require-number-to-fixed-digits-argument': ['error'],
        'unicorn/require-passive-events': ['error'],
        // Custom.
        'unicorn/require-post-message-target-origin': ['error'],
        'unicorn/require-proxy-trap-boolean-return': ['error'],
        // Custom: a short comment stays on one line (`/** Full turn, in degrees. */`).
        'unicorn/single-line-block-comment-style': ['error', 'single-line'],
        'unicorn/string-content': ['off'],
        'unicorn/switch-case-braces': ['error'],
        'unicorn/switch-case-break-position': ['error'],
        // Off: formatting is Prettier's job.
        'unicorn/template-indent': ['off'],
        'unicorn/text-encoding-identifier-case': ['error'],
        'unicorn/throw-new-error': ['error'],
        // Custom.
        'unicorn/try-complexity': ['error'],
      },
    },
    // Specs feed `null` on purpose; benchmarks write results to a module-level sink; configs mirror JSON.
    {
      name: 'unicorn/tooling-and-tests',
      files: ['**/*.spec.ts', '**/testing/**', '**/*.bench.ts', '**/*.mjs', '**/*.mts'],
      rules: {
        'unicorn/no-null': ['off'],
        'unicorn/no-top-level-assignment-in-function': ['off'],
        // Off: `expect(…).rejects.toThrow(expect.objectContaining(…))` is idiomatic.
        'unicorn/max-nested-calls': ['off'],
      },
    },
  ];
}
