// Strings: case conversion, word splitting, truncation, escaping, templating, number extraction.

export { extractNumber } from './extract-number';
export { extractNumbers } from './extract-numbers';
export { splitWords } from './split-words';
export { capitalize } from './capitalize';
export { camelCase } from './camel-case';
export { pascalCase } from './pascal-case';
export { kebabCase } from './kebab-case';
export { snakeCase } from './snake-case';
export { constantCase } from './constant-case';
export { titleCase } from './title-case';
export { sentenceCase } from './sentence-case';
export { truncate } from './truncate';
export { slugify } from './slugify';
export { escapeHtml } from './escape-html';
export { escapeRegExp } from './escape-reg-exp';
export { formatTemplate } from './format-template';
export { lowerCase } from './lower-case';
export { upperCase } from './upper-case';
export { dotCase } from './dot-case';
export { trainCase } from './train-case';
export { uncapitalize } from './uncapitalize';
export { removeDiacritics } from './remove-diacritics';
export { isBlank } from './is-blank';
export { squish } from './squish';
export { pluralize } from './pluralize';
export { toCsv } from './to-csv';
export { createIdGenerator } from './create-id-generator';
