// Generates the function catalog from the sources: the "Functions" section of README.md (one line per export)
// and docs/FUNCTIONS.md (with the files each export needs, to copy a function into another project).

import fs from 'node:fs';
import path from 'node:path';

const SOURCE_DIRECTORY = 'src';
const README_FILE = 'README.md';
const CATALOG_FILE = 'docs/FUNCTIONS.md';
const START_MARKER = '<!-- functions:start -->';
const END_MARKER = '<!-- functions:end -->';
const EXPORT_PATTERN = /^export (?<isType>type )?\{ (?<name>\w+) \} from '\.\/(?<file>[\w\-.\/]+)';$/gmv;
const IMPORT_PATTERN = /^import (?:type )?\{[^\}]*\} from '(?<specifier>\.[^']+)';$/gmv;
const DOC_PATTERN =
  /\/\*\*(?<jsdoc>(?:(?!\*\/)[\s\S])*)\*\/\s*export (?:declare )?(?:async )?(?:class|enum|function\*?|interface|type) /v;
const DESCRIPTION_PATTERN = /^\/\/ (?<description>.+)$/mv;

/**
 * Lists the local files a source file imports, transitively.
 *
 * @param file - Path of the source file.
 * @param seen - Files already collected.
 * @returns The dependencies, relative to `src/`, sorted.
 */
function dependenciesOf(file, seen = new Set()) {
  const source = fs.readFileSync(file, 'utf8');
  for (const { groups } of source.matchAll(IMPORT_PATTERN)) {
    const dependency = path.join(path.dirname(file), groups.specifier);
    if (!seen.has(dependency)) {
      seen.add(dependency);
      dependenciesOf(dependency, seen);
    }
  }
  return [...seen].map((dependency) => path.relative(SOURCE_DIRECTORY, dependency)).toSorted();
}

/**
 * Reads the first sentence of the JSDoc of the export of a file.
 *
 * @param source - Content of the file.
 * @returns The summary, on one line, with `|` escaped for Markdown tables.
 */
function summaryOf(source) {
  const jsdoc = DOC_PATTERN.exec(source)?.groups?.jsdoc ?? '';
  const description = jsdoc
    .split('\n')
    .map((line) => line.replace(/^\s*\*\s?/v, ''))
    .join(' ')
    .split(/ @[a-z]/v, 1)[0]
    .trim();
  const [sentence] = description.split(/(?<=\.)\s/v, 1);
  return (sentence ?? description).replaceAll('|', String.raw`\|`);
}

/**
 * Reads the exports of every folder of `src/`, from its `index.ts`.
 *
 * @returns The folders, with their description and their exports sorted by name.
 */
function readFolders() {
  return fs
    .readdirSync(SOURCE_DIRECTORY, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && fs.existsSync(path.join(SOURCE_DIRECTORY, entry.name, 'index.ts')))
    .map((entry) => entry.name)
    .toSorted()
    .map((folder) => {
      const index = fs.readFileSync(path.join(SOURCE_DIRECTORY, folder, 'index.ts'), 'utf8');
      const exports = [...index.matchAll(EXPORT_PATTERN)]
        .map(({ groups }) => {
          const file = path.join(SOURCE_DIRECTORY, folder, groups.file);
          const source = fs.readFileSync(file, 'utf8');
          return { name: groups.name, file, isType: groups.isType !== undefined, summary: summaryOf(source) };
        })
        .toSorted((a, b) => a.name.localeCompare(b.name, 'en'));
      return { folder, description: DESCRIPTION_PATTERN.exec(index)?.groups?.description ?? '', exports };
    });
}

/**
 * Names an export in a Markdown table, with a link to its file.
 *
 * @param entry - The export.
 * @param root - Relative path from the Markdown file to the repository root.
 * @returns The linked name, suffixed with its kind for a type.
 */
function linkOf(entry, root) {
  return `[\`${entry.name}\`](${root}${entry.file})${entry.isType ? ' _(type)_' : ''}`;
}

const folders = readFolders();

const readmeLines = [START_MARKER, ''];
for (const { folder, description, exports } of folders) {
  readmeLines.push(`### ${folder}`, '', description, '', '| Export | What it does |', '| --- | --- |');
  for (const entry of exports) {
    readmeLines.push(`| ${linkOf(entry, '')} | ${entry.summary} |`);
  }
  readmeLines.push('');
}
readmeLines.push(END_MARKER);
const readme = fs.readFileSync(README_FILE, 'utf8');
const start = readme.indexOf(START_MARKER);
const end = readme.indexOf(END_MARKER) + END_MARKER.length;
fs.writeFileSync(README_FILE, readme.slice(0, start) + readmeLines.join('\n') + readme.slice(end));

const catalogLines = [
  '# Functions',
  '',
  '<!-- Generated by `pnpm docs:catalog` from the JSDoc of the sources: do not edit by hand. -->',
  '',
  'Every public function, class, enum and type, one file each. **Needs** lists the other files of `src/` to',
  'copy along when a file is copied alone into another project.',
  '',
];
for (const { folder, description, exports } of folders) {
  catalogLines.push(`## ${folder}`, '', description, '', '| Export | Summary | Needs |', '| --- | --- | --- |');
  for (const entry of exports) {
    const needs = dependenciesOf(entry.file)
      .map((dependency) => `\`${dependency}\``)
      .join(', ');
    catalogLines.push(`| ${linkOf(entry, '../')} | ${entry.summary} | ${needs || '—'} |`);
  }
  catalogLines.push('');
}
fs.writeFileSync(CATALOG_FILE, catalogLines.join('\n'));

const count = folders.reduce((total, { exports }) => total + exports.length, 0);
// eslint-disable-next-line no-console -- a command-line script reports its result.
console.info(`${README_FILE} and ${CATALOG_FILE}: ${count} exports.`);
